columns:
  date: datetime64[ns]
  open: float64
  high: float64
  low: float64
  close: float64
  volume: int64

numerical_columns:
  - open
  - high
  - low
  - close
  - volume

categorical_columns: []

target_columns:
  - open
  - high
  - low
  - close

drop_columns:
  - date

required_columns:
  - date
  - open
  - high
  - low
  - close
  - volume

data_validation:
  duplicate_check: true
  null_check: true

column_ranges:
  open:
    min: 0
  high:
    min: 0
  low:
    min: 0
  close:
    min: 0
  volume:
    min: 0