import os
from from_root import from_root
from datetime import date


DATABASE_NAME = "Market_mind"
COLLECTION_NAME = "SP500_Data"


PIPELINE_NAME: str = ""
ARTIFACT_DIR: str = "artifact"

MODEL_FILE_NAME = "model.pth"

CURRENT_YEAR = date.today().year
PREPROCSSING_OBJECT_FILE_NAME = "preprocessing.pkl"

FILE_NAME: str = "data.csv"
TRAIN_FILE_NAME: str = "train.csv"
TEST_FILE_NAME: str = "test.csv"
SCHEMA_FILE_PATH = os.path.join("src","config", "schema.yaml")


FEATURE_CONFIG_PATH=os.path.join("src","config","feature_config.yaml")

AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
REGION_NAME = "us-east-1"


"""
Data Ingestion related constant start with DATA_INGESTION VAR NAME
"""
DATA_INGESTION_COLLECTION_NAME: str = "ProjStockPred_Data"
DATA_INGESTION_DIR_NAME: str = "data_ingestion"
DATA_INGESTION_RAW_DATA_DIR: str = "raw_data"
DATA_INGESTION_INGESTED_DIR: str = "ingested"
DATA_INGESTION_TRAIN_END_DATE="2023-01-01"
DATA_INGESTION_VALIDATION_END_DATE="2023-01-01"

"""
Data Validation realted contant start with DATA_VALIDATION VAR NAME
"""
DATA_VALIDATION_DIR_NAME: str = "data_validation"
DATA_VALIDATION_REPORT_FILE_NAME: str = "report.yaml"

"""
Data Transformation ralated constant start with DATA_TRANSFORMATION VAR NAME
"""
WALK_FORWARD_FOLD_DIR_NAME="walk_forward_fold"
WALK_FORWARD_FOLD_METADATA_FILE_NAME="walkforward_folds_metadata.json"


"""
Feature Engineering realted constants
"""
FEATURE_ENGINEERING_DIR_NAME:str="feature_engineering"
FEATURE_ENGINEERING_RAW_DIR_NAME:str="raw_data"
FEATURE_ENGINEERING_RAW_FILE_NAME:str='feature_engineered_raw_data.csv'


"""
MODEL TRAINER related constant start with MODEL_TRAINER var name
"""
MODEL_TRAINER_DIR_NAME: str = "model_trainer"
MODEL_TRAINER_TRAINED_MODEL_DIR: str = "trained_model"
MODEL_TRAINER_TRAINED_MODEL_NAME: str = "best_model.pth"
MODEL_TRAINER_INPUT_SIZE:int=8
MODEL_TRAINER_HIDDEN_SIZE:int=128
MODEL_TRAINER_NUM_LAYERS:int=2
MODEL_TRAINER_OUTPUT_SIZE:int=4
MODEL_TRAINER_BATCH_SIZE:int=512
MODEL_TRAINER_SEQUENCE_LENGTH:int=60
MODEL_TRAINER_DROPOUT:float=0.2
MODEL_TRAINER_OPTIMIZER:str="Adam"
MODEL_TRAINER_EPOCHS:int=25
MODEL_TRAINER_LEARNING_RATE:float=1e-3
MODEL_TRAINER_LOSS_FUNCTION:str='SmoothL1Loss'
MODEL_TRAINER_PATIENCE:int=5
MODEL_TRAINER_DEVICE:str="cuda"
MODEL_TRAINER_GRADIENT_CLIP:float=1.0



MODEL_TRAINER_TREE_MODELS_N_ESTIMATORS=300
MODEL_TRAINER_TREE_MODELS_MAX_DEPTH=3
MODEL_TRAINER_TREE_MODELS_LEARNING_RATE=0.03
MODEL_TRAINER_TREE_MODELS_SUBSAMPLE=0.8
MODEL_TRAINER_TREE_MODELS_COLSAMPLE_BYTREE=0.8
MODEL_TRAINER_TREE_MODELS_REG_ALPHA=0.1
MODEL_TRAINER_TREE_MODELS_REG_LAMBDA=0.1
MODEL_TRAINER_TREE_MODELS_N_JOBS=-1
MODEL_TRAINER_TREE_MODELS_RANDOM_STATE=42
MODEL_TRAINER_TREE_MODELS_EARLYSTOPPING_ROUNDS=20
MODEL_TRAINER_TREE_MODELS_CAT_BOOST_L2_LEAF_REG=5.0

UNIFIED_DEEP_ENCODER_TRANSFORMER_MODEL_DIM=32
UNIFIED_DEEP_ENCODER_TRANSFORMER_NUM_HEADS=4
UNIFIED_DEEP_ENCODER_TRANSFORMER_NUM_LAYERS=1
UNIFIED_DEEP_ENCODER_TRANSFORMER_DROPOUT=0.4
UNIFIED_DEEP_ENCODER_TRANSFORMER_HIDDEN_DIM=32
UNIFIED_DEEP_ENCODER_TRANSFORMER_HORIZONS=4
UNIFIED_DEEP_ENCODER_TRANSFORMER_EMBED_DIM=48
HYBRID_HORIZON_LOSS_APLHA=0.2

SEQ_LEN = 60
EPOCHS = 25
MAX_GRAD_NORM = 1.0
TRANSACTION_COST_BPS = 10
TOP_N = 20
MIN_TRAIN_YEARS = 2      # minimum calendar years of history required before the first fold
MAX_FOLDS = None         # set an int to cap the number of folds while iterating quickly; None = all available


"""
MODEL Evaluation related constants
"""
MODEL_EVALUATION_CHANGED_THRESHOLD_SCORE: float = 0.02
MODEL_BUCKET_NAME = "my-model-mlopsproj2004"
MODEL_PUSHER_S3_KEY = "model-registry"


APP_HOST = "0.0.0.0"
APP_PORT = 5000